"""create_initial_tables

Revision ID: 0ac366912ad2
Revises: 
Create Date: 2026-03-09 18:50:39.468693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac366912ad2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vessels',
    sa.Column('mmsi', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('imo', sa.String(), nullable=True),
    sa.Column('vessel_type', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('mmsi'),
    sa.UniqueConstraint('imo')
    )
    op.create_index(op.f('ix_vessels_mmsi'), 'vessels', ['mmsi'], unique=False)
    op.create_table('oil_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('estimated_area', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detection_date', sa.DateTime(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmation_date', sa.DateTime(), nullable=True),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='check_latitude'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='check_longitude'),
    sa.CheckConstraint('confidence_level >= 0 AND confidence_level <= 100', name='check_confidence_level'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oil_feature_vessels',
    sa.Column('oil_feature_id', sa.UUID(), nullable=False),
    sa.Column('vessel_mmsi', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['oil_feature_id'], ['oil_features.id'], ),
    sa.ForeignKeyConstraint(['vessel_mmsi'], ['vessels.mmsi'], ),
    sa.PrimaryKeyConstraint('oil_feature_id', 'vessel_mmsi')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oil_feature_vessels')
    op.drop_table('oil_features')
    op.drop_index(op.f('ix_vessels_mmsi'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
